
spring:
  application:
    name: data-service
  data:
    cassandra:
      keyspace-name: testdb
      contact-points: localhost
      schema-action: CREATE_IF_NOT_EXISTS
      port: 9042

    datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:localhost;DB_CLOSE_ON_EXIT=FALSE
      username: admin
      password:
  batch:
    initialize-schema: always

server:
  port: 8300

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8302/eureka
  instance:
    hostname: localhost

logstash:
  host: localhost

cassandra:
  basepackages: com.emprovise.service.dataservice
---
spring:
  profiles: production
  data:
    cassandra:
      contact-points: cassandra-service
      port: 9042
      username: appuser
      password: test123

logstash:
  host: logstash-service
