apiVersion: v1
kind: ConfigMap
metadata:
  name: cassandra
data:
  database-name: testdb
---

apiVersion: v1
kind: Secret
metadata:
  name: cassandra
type: Opaque
data:
  database-user: YWRtaW4=
  database-password: YWRtaW4xMjM=
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: cassandra-initdb
data:
  init-db.cql: |

    DROP keyspace testdb;
    CREATE KEYSPACE testdb WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'} AND durable_writes = true;
    ALTER USER cassandra WITH PASSWORD 'admin123';
    CREATE USER appuser WITH PASSWORD 'test123';
    GRANT ALL ON KEYSPACE testdb TO appuser;
---
apiVersion: v1
kind: Service
metadata:
  name: cassandra-service
spec:
  type: NodePort
  ports:
    - name: cql
      port: 9042
    nodePort: 32241
  selector:
    app: cassandra
---
apiVersion: "apps/v1beta1"
kind: StatefulSet
metadata:
  name: cassandra
spec:
  serviceName: cassandra
  replicas: 6
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                app: cassandra
      containers:
        - env:
            - name: MAX_HEAP_SIZE
              value: 512M
            - name: HEAP_NEWSIZE
              value: 512M
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: CASSANDRA_INITDB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: cassandra
                  key: database-name
            - name: CASSANDRA_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cassandra
                  key: database-user
            - name: CASSANDRA_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cassandra
                  key: database-password

          image: merapar/cassandra:2.3
          name: cassandra
          volumeMounts:
            - mountPath: /cassandra-storage
              name: cassandra-storage
      volumes:
        - name: cassandra-initdb
          configMap:
            name: cassandra-initdb

  volumeClaimTemplates:
  - metadata:
      name: cassandra-storage
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi

