
server:
  port: 8309

spring:
  application:
    name: s3-service

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8302/eureka
  instance:
    hostname: localhost

cloud:
  minio:
    endpoint: http://192.168.84.82:9000
    accessKey: admin
    secretKey: minio123

---
spring:
  profiles: production

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8302/eureka
  instance:
    preferIpAddress: true

cloud:
  minio:
    endpoint: http://minio-service:9000
    accessKey: minio
    secretKey: minio123

