apiVersion: v1
kind: ServiceAccount
metadata:
  name: nfs-client-provisioner
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nfs-client-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: quay.io/external_storage/nfs-client-provisioner:latest
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: emprovise/nfs
            - name: NFS_SERVER
              value: 10.10.10.60      # Update NFS_SERVER value with IP Address of NFS Server
            - name: NFS_PATH
              value: /mnt/kubernetes
      volumes:
        - name: nfs-client-root
          nfs:
            server: 10.10.10.60      # Update NFS_SERVER value with IP Address of NFS Server
            path: /mnt/kubernetes
