
spring:
  application:
    name: storage-service

server:
  port: 8309

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8302/eureka
  instance:
    hostname: localhost

cloud:
  minio:
    endpoint: http://10.141.130.18:9000
    accessKey: minio
    secretKey: minio123

logstash:
  host: localhost

---
spring:
  profiles: production

cloud:
  minio:
    endpoint: http://minio-service:9000
    accessKey: minio
    secretKey: minio123

logstash:
  host: logstash-service

